#!/usr/bin/env bash

# Exit on error
set -e

# Number of parallel jobs + arm64 only
jobs=$(sysctl -n hw.activecpu)
export BUILD_ARM64=True

# Build libcdio
cd tools

./build-codecs libcdio libcdio-paranoia

cp libcdio-2.3.0/lib/driver/.libs/libcdio.19.dylib libcdio.19.dylib
cp libcdio-paranoia-10.2+2.0.2/lib/cdda_interface/.libs/libcdio_cdda.2.dylib libcdio_cdda.2.dylib
cp libcdio-paranoia-10.2+2.0.2/lib/paranoia/.libs/libcdio_paranoia.2.dylib libcdio_paranoia.2.dylib

sudo cp libcdio*.dylib /usr/local/lib

cd ..

# Build smooth
cd smooth

make  -j$jobs
sudo make -j$jobs install

cd ..

# Build BoCA
cd boca

make -j$jobs
sudo make -j$jobs install

cd ..

# Build fre:ac
make -j$jobs
sudo make -j$jobs install

# Build codecs and DSP libraries
cd tools

./build-codecs faad2 mp4v2
./build-codecs lame mpg123
./build-codecs libogg opus speex vorbis
./build-codecs flac mac musepack wavpack
./build-codecs ffmpeg libsndfile
./build-codecs libsamplerate rnnoise rubberband

cp faad2-2.11.2/libfaad.2.dylib libfaad.2.dylib
cp mp4v2-2.1.3/.libs/libmp4v2.2.dylib libmp4v2.2.dylib
cp lame-3.100/libmp3lame/.libs/libmp3lame.0.dylib libmp3lame.0.dylib
cp mpg123-1.33.4/src/libmpg123/.libs/libmpg123.0.dylib libmpg123.0.dylib
cp libogg-1.3.6/src/.libs/libogg.0.dylib libogg.0.dylib
cp opus-1.6.1/.libs/libopus.0.dylib libopus.0.dylib
cp speex-1.2.1/libspeex/.libs/libspeex.1.dylib libspeex.1.dylib
cp libvorbis-1.3.7/lib/.libs/libvorbis.0.dylib libvorbis.0.dylib
cp libvorbis-1.3.7/lib/.libs/libvorbisenc.2.dylib libvorbisenc.2.dylib
cp flac-1.5.0/src/libFLAC/.libs/libFLAC.14.dylib libFLAC.14.dylib
cp MAC_1235_SDK/libMAC.14.dylib libMAC.14.dylib
cp libsndfile-1.2.2/src/.libs/libsndfile.1.dylib libsndfile.1.dylib
cp libsamplerate-0.2.2/src/.libs/libsamplerate.0.dylib libsamplerate.0.dylib
cp rnnoise-9acc1e5/.libs/librnnoise.0.dylib librnnoise.0.dylib
cp rubberband-1.8.2/lib/librubberband.dylib librubberband.dylib

cp musepack_src_r475/mpcdec/mpcdec mpcdec
cp musepack_src_r475/mpcenc/mpcenc mpcenc
cp wavpack-5.8.1/cli/wavpack wavpack
cp wavpack-5.8.1/cli/wvunpack wvunpack
cp ffmpeg-8.0.1/ffmpeg ffmpeg

sudo cp lib*.dylib /usr/local/lib
sudo cp ffmpeg mpc* w*pack /usr/local/bin

cd ..

# Prepare package
cd packaging/macosx

bash ./prepare.sh
bash ./package.sh

MACOSX_TARGET=$MACOSX_DEPLOYMENT_TARGET
if [[ -z $MACOSX_TARGET ]]; then
  MACOSX_TARGET=`sw_vers | awk '$1 == "ProductVersion:" { print $2 }'`
fi

mv freac-*-macos${MACOSX_TARGET%%.*}.dmg ../../freac-continuous-macos${MACOSX_TARGET%%.*}.dmg

cd ../..